### PR TITLE
Suggested revisions

### PR DESCRIPTION
**Pull request by nathanfdunn**
Cleaned up case statements and made the section of the README that explains when bootstrap and font awesome are included more explicit.

### CODE REVIEW

**Comment by natewallace** [comment]
The updated README.md sentence makes sense.  I'm not sure I agree with the changes to the default statements in the switch blocks.  I feel it's better to handle values explicitly rather than default to a value that may not have been selected.  The defaults here are meant to account for the possibility of new selection values being added in the future.

**Comment by nathanfdunn** [comment]
In that case do you think appropriate behavior would be for the `default` path to throw an exception?

**Comment by natewallace** [comment]
Normally I would throw exceptions for unexpected values but I don't think they are necessary here.  

The first two switch blocks are simply white listing the scenarios where the app will prompt for the inclusion of additional style resources.  If a new selection value is added this code might not need to be touched.

The last switch block maps selected values to the components that will get setup for the project.  If a new selection value is added and this code isn't updated the project would be setup without any components.

I think both scenarios are ok.

**Comment by nathanfdunn** [comment]
You've convinced me!

**Pull request closed without merging**
